# permissions for end users to edit serviceproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceproxy-editor-role
rules:
- apiGroups:
  - stable.dfds.cloud
  resources:
  - serviceproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.dfds.cloud
  resources:
  - serviceproxies/status
  verbs:
  - get
