apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inventa-cluster-serviceproxy-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inventa-serviceproxy-admin
subjects:
- kind: ServiceAccount
  name: inventa-operator
  namespace: NAMESPACE-REPLACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inventa-cluster-read-and-watch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inventa-read-and-watch
subjects:
- kind: ServiceAccount
  name: inventa-operator
  namespace: NAMESPACE-REPLACE