apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventa-read-and-watch
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - 'list'
  - 'get'
  - 'watch'
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - 'list'
  - 'get' 
  - 'watch'
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - 'list'
  - 'get' 
  - 'watch'