apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceproxy-crud-dev
  namespace: developerautomation-xavgy
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developerautomation-serviceproxy-crud-dev
  namespace: developerautomation-xavgy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: serviceproxy-crud-dev
subjects:
- kind: Group
  name: developerautomation-xavgy
- kind: ServiceAccount
  name: serviceproxy-operator
  namespace: developerautomation-xavgy  