apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventa-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inventa-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
            
  selector:
    {{- include "inventa-operator.selectorLabels" . | nindent 4 }}
