openapi: 3.0.3
info:
  title: inventa-operator
  description: 'Contains the API documentation for the inventa-operator HTTP API.'
  contact:
    name: DFDS A/S
    url: https://github.com/dfds
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about inventa-operator
  url: https://github.com/dfds/inventa
servers:
- url: http://localhost:8090
tags:
- name: Object data
  description: Kubernetes objects in your cluster
paths:
  /api/get-all:
    get:
      tags:
      - Object data
      summary: Get all Ingress and Service objects from cluster
      operationId: getAll
      responses:
        500:
          description: Internal server error
          content: {}
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAll'          
      security:
      - azuread_auth:
        - .default
components:
  schemas:
    GetAll:
      type: object
      properties:
        ingress:
          type: object
        service:
          type: object
  securitySchemes:
    azuread_auth:
      type: openIdConnect
      name: authorization
      in: header
      scheme: Bearer
      openIdConnectUrl: https://login.microsoftonline.com/TENANT-ID-HERE/v2.0/.well-known/openid-configuration
